from .db import db
from .AdresModel import Adres
from .IlModel import Il
from .IlceModel import Ilce
from .KargoModel import Kargo
from .AliciBilgileriModel import AliciBilgileri
from .KargoBilgileriModel import KargoBilgileri
from .GondericiBilgileriModel import GondericiBilgileri
from .SubeBilgileriModel import SubeBilgileri
