"""ilk migrate

Revision ID: 150861201a92
Revises: 
Create Date: 2022-12-03 16:47:00.019620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150861201a92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('il',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilAdi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ilceler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ilceadi', sa.String(), nullable=True),
    sa.Column('ilId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ilId'], ['il.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adresler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adres_turu', sa.String(), nullable=True),
    sa.Column('adres', sa.String(), nullable=True),
    sa.Column('ilId', sa.Integer(), nullable=True),
    sa.Column('ilceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ilId'], ['il.id'], ),
    sa.ForeignKeyConstraint(['ilceId'], ['ilceler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aliciBilgileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adres_id', sa.Integer(), nullable=True),
    sa.Column('tcKimlik', sa.String(length=11), nullable=True),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('soyad', sa.String(), nullable=True),
    sa.Column('telNo', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['adres_id'], ['adresler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gondericiBilgileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adres_id', sa.Integer(), nullable=True),
    sa.Column('tcKimlik', sa.String(length=11), nullable=True),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('soyad', sa.String(), nullable=True),
    sa.Column('telNo', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['adres_id'], ['adresler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subeBilgileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad', sa.String(), nullable=True),
    sa.Column('adres_id', sa.Integer(), nullable=True),
    sa.Column('telNo', sa.String(length=11), nullable=True),
    sa.Column('sube_yetkilisi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['adres_id'], ['adresler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kargoBilgileri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alici_id', sa.Integer(), nullable=True),
    sa.Column('gonderici_id', sa.Integer(), nullable=True),
    sa.Column('sube_id', sa.Integer(), nullable=True),
    sa.Column('kargo_tarihi', sa.DateTime(), nullable=True),
    sa.Column('kargo_odemeTuru', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alici_id'], ['aliciBilgileri.id'], ),
    sa.ForeignKeyConstraint(['gonderici_id'], ['gondericiBilgileri.id'], ),
    sa.ForeignKeyConstraint(['sube_id'], ['subeBilgileri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kargoBilgileri')
    op.drop_table('subeBilgileri')
    op.drop_table('gondericiBilgileri')
    op.drop_table('aliciBilgileri')
    op.drop_table('adresler')
    op.drop_table('ilceler')
    op.drop_table('il')
    # ### end Alembic commands ###
