"""empty message

Revision ID: 7e04ab339ca1
Revises: 850a45c107a0
Create Date: 2022-12-25 13:11:13.360841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e04ab339ca1'
down_revision = '850a45c107a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kargoBilgileri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kargoId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aliciId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gondericiId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subeId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('kargoBilgileri_alici_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('kargoBilgileri_gonderici_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('kargoBilgileri_kargo_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('kargoBilgileri_sube_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subeBilgileri', ['subeId'], ['id'])
        batch_op.create_foreign_key(None, 'aliciBilgileri', ['aliciId'], ['id'])
        batch_op.create_foreign_key(None, 'kargo', ['kargoId'], ['id'])
        batch_op.create_foreign_key(None, 'gondericiBilgileri', ['gondericiId'], ['id'])
        batch_op.drop_column('alici_id')
        batch_op.drop_column('gonderici_id')
        batch_op.drop_column('sube_id')
        batch_op.drop_column('kargo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kargoBilgileri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kargo_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sube_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gonderici_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alici_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('kargoBilgileri_sube_id_fkey', 'subeBilgileri', ['sube_id'], ['id'])
        batch_op.create_foreign_key('kargoBilgileri_kargo_id_fkey', 'kargo', ['kargo_id'], ['id'])
        batch_op.create_foreign_key('kargoBilgileri_gonderici_id_fkey', 'gondericiBilgileri', ['gonderici_id'], ['id'])
        batch_op.create_foreign_key('kargoBilgileri_alici_id_fkey', 'aliciBilgileri', ['alici_id'], ['id'])
        batch_op.drop_column('subeId')
        batch_op.drop_column('gondericiId')
        batch_op.drop_column('aliciId')
        batch_op.drop_column('kargoId')

    # ### end Alembic commands ###
