"""empty message

Revision ID: 850a45c107a0
Revises: a05eba6904a6
Create Date: 2022-12-22 13:26:50.187670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850a45c107a0'
down_revision = 'a05eba6904a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kargoBilgileri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kargo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'kargo', ['kargo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kargoBilgileri', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('kargo_id')

    # ### end Alembic commands ###
